require:
  - rubocop-performance
  - rubocop-rails
AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
Style/FrozenStringLiteralComment: { Enabled: false }
Style/MutableConstant: { Enabled: false }
Metrics/LineLength: {AutoCorrect: false, Max: 120}
Style/SymbolArray: { Enabled: false }
Style/WordArray: { Enabled: false }
Style/RescueStandardError: { Enabled: false }
Style/IfUnlessModifier: { Enabled: false }
Style/BracesAroundHashParameters: { Enabled: false }
Style/ParenthesesAroundCondition: { Enabled: false }
Style/RedundantParentheses: { Enabled: false }
Style/TernaryParentheses: { Enabled: false }
